# Generated by Django 4.1.7 on 2023-05-10 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sname", models.CharField(max_length=20)),
                ("sid", models.IntegerField()),
                ("scourse", models.CharField(max_length=30)),
                ("sage", models.IntegerField()),
            ],
        ),
    ]
